"""Build the consolidated model and render a self-contained HTML dashboard."""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from consolidate import (  # noqa: E402
    AS_OF_MONTH, AS_OF_YEAR, build_report, load_budget, load_facts,
    write_consolidated_csv,
)


def _money(x):
    return f"${x:,.0f}"


def render_html(report) -> str:
    s = report["summary"]
    head = (
        "<style>body{font-family:Segoe UI,Arial,sans-serif;margin:2rem;color:#222}"
        "h1{font-size:1.4rem}table{border-collapse:collapse;width:100%;margin:1rem 0}"
        "th,td{padding:.5rem .75rem;border-bottom:1px solid #eee;text-align:right}"
        "th:first-child,td:first-child{text-align:left}thead th{border-bottom:2px solid #333}"
        ".pos{color:#137333}.neg{color:#a50e0e}.cards{display:flex;gap:1rem;flex-wrap:wrap}"
        ".card{background:#f5f7fa;border-radius:8px;padding:1rem 1.25rem;min-width:160px}"
        ".card .v{font-size:1.4rem;font-weight:600}.bar{height:14px;border-radius:7px;"
        "background:#2b6cb0;display:inline-block}</style>"
    )
    cards = (
        f"<div class='cards'>"
        f"<div class='card'><div>YTD Revenue</div><div class='v'>{_money(s['ytd_revenue'])}</div></div>"
        f"<div class='card'><div>YTD Expenses</div><div class='v'>{_money(s['ytd_expenses'])}</div></div>"
        f"<div class='card'><div>YTD Net</div><div class='v'>{_money(s['ytd_net'])}</div></div>"
        f"<div class='card'><div>Entities</div><div class='v'>{len(s['entities'])}</div></div>"
        f"</div>"
    )
    rows_html = ""
    for r in report["rows"]:
        vcls = "pos" if r["variance"] >= 0 else "neg"
        ycls = "pos" if r["yoy_pct"] >= 0 else "neg"
        rows_html += (
            f"<tr><td>{r['category']}</td>"
            f"<td>{_money(r['ytd_actual'])}</td>"
            f"<td>{_money(r['ytd_budget'])}</td>"
            f"<td class='{vcls}'>{_money(r['variance'])} ({r['variance_pct']:+.1f}%)</td>"
            f"<td>{_money(r['mtd'])}</td>"
            f"<td>{_money(r['py_ytd'])}</td>"
            f"<td class='{ycls}'>{r['yoy_pct']:+.1f}%</td></tr>"
        )
    table = (
        "<table><thead><tr><th>Category</th><th>YTD Actual</th><th>YTD Budget</th>"
        "<th>Variance</th><th>MTD</th><th>PY YTD</th><th>YoY</th></tr></thead>"
        f"<tbody>{rows_html}</tbody></table>"
    )
    # simple revenue-vs-expense bar
    rev, exp = s["ytd_revenue"], s["ytd_expenses"]
    scale = 400 / (rev or 1)
    bars = (
        f"<p>Revenue <span class='bar' style='width:{rev*scale:.0f}px'></span> {_money(rev)}<br>"
        f"Expenses <span class='bar' style='width:{exp*scale:.0f}px;background:#c05621'></span> {_money(exp)}</p>"
    )
    return (
        f"<html><head>{head}</head><body>"
        f"<h1>Consolidated Financial Dashboard — {', '.join(s['entities'])}</h1>"
        f"<p>As of {AS_OF_YEAR}-{AS_OF_MONTH:02d} · standardized chart of accounts</p>"
        f"{cards}{bars}<h2>By category</h2>{table}"
        f"<p style='color:#888;font-size:.85rem'>Generated by the consolidation "
        f"accelerator (offline sample). The real model runs in Microsoft Fabric / "
        f"Power BI — see dax-library.md.</p></body></html>"
    )


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    data = os.path.join(here, "data")
    if not os.path.exists(os.path.join(data, "transactions.csv")):
        import generate_data
        generate_data.main()
    facts = load_facts(data)
    budget = load_budget(data)
    report = build_report(facts, budget)

    out = os.path.join(here, "out")
    os.makedirs(out, exist_ok=True)
    write_consolidated_csv(facts, os.path.join(out, "consolidated.csv"))
    with open(os.path.join(out, "dashboard.html"), "w", encoding="utf-8") as fh:
        fh.write(render_html(report))

    s = report["summary"]
    print(f"Entities: {', '.join(s['entities'])}")
    print(f"YTD Revenue {_money(s['ytd_revenue'])} · Expenses "
          f"{_money(s['ytd_expenses'])} · Net {_money(s['ytd_net'])}")
    for r in report["rows"]:
        print(f"  {r['category']:10} YTD {_money(r['ytd_actual']):>10} "
              f"vs budget {r['variance_pct']:+.1f}%  YoY {r['yoy_pct']:+.1f}%")
    print(f"\nWrote: {out}/dashboard.html  and  {out}/consolidated.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
